# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - OKRNeudesicTest

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
          include-prerelease: true

      - name: dotnet build and publish
        run: |
          cd scr/api/auction-api/auction-api/
          dotnet restore
          dotnet build --configuration Release

      - name: dotnet publish
        run: |
          cd scr/api/auction-api/auction-api/
          dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload API Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: APIApp
          path: "./scr/api/auction-api/auction-api//bin/net5.0"
          if-no-files-found: error
          retention-days: 30

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "OKRNeudesicTest"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E6004DF11DD94860B81FB016D4D4A06C }}
          package: .
