# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - AuctionFrontEnd

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: npm install, build, and test
        run: |
          cd scr/front-end/auction-website/
          npm install
          npm run build --if-present

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: WebApp
          path: "scr/front-end/auction-website/build"
          if-no-files-found: error
          retention-days: 30

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - run: |
        az webapp list --query "[?state=='Running']"

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: WebApp

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "AuctionFrontEnd"
          package: ./WebApp
